### ISSUE TITLE
Ansible Inventory Input Example

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#292]
I am having some troubles specifying an Ansible host using the inventory input. 
Do you mind providing an example resp. fix my ensemble?

For this issue, we might use the following ensemble.

````yaml
apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    node_types:
      host:
        derived_from: tosca:Root

        attributes:
          public_address:
            type: string
            default: default_public_address

        capabilities:
          host:
            type: tosca.capabilities.Compute
                
        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
                operation_host: ORCHESTRATOR
              inputs:
                resultTemplate: |
                  - name: SELF
                    attributes:
                      public_address: "{{ outputs.public_address | trim }}"  
                playbook:
                  q:
                  - name: Sets a fact
                    set_fact:
                      public_address: ansible_public_address
              outputs:
                public_address:

      app:
        derived_from: tosca.nodes.SoftwareComponent

        properties:
          os_ssh_user:
            type: string
            default: ubuntu

          os_ssh_key_file:
            type: string
            default: /path/to/ssh/key/file

        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
              inputs:
                inventory: 
                  all:
                    hosts:
                      host:
                        ansible_host: hardcoded_ansible_host
                        #ansible_host: {eval: '.::..::.requirements[.name=host]::.target::public_address'}
                        ansible_connection: ssh
                    vars: {}
                    children: {}

                playbook:
                  q:
                  - name: Wait for ssh
                    wait_for_connection:
                playbookArgs:
                - --key-file={{ SELF.os_ssh_key_file }}
                - --user={{ SELF.os_ssh_user }}
                - --ssh-common-args="-o IdentitiesOnly=yes -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"


    topology_template:
      node_templates:
        host:
          type: host

        app:
          type: app
          requirements:
          - host: host
````

When trying to generate the deployment plan, it throws an parsing error.
I tried this with Unfurl 0.9.1 and Unfurl 1.0.0.

````shell
(.venv) stoetzms@storm:~/unfurl-ansible-host$ unfurl plan
   INFO   UNFURL Using home project at: "/home/stoetzms/.unfurl_home/unfurl.yaml"
   INFO   UNFURL Loaded project at /home/stoetzms/unfurl-ansible-host/unfurl.yaml
   INFO   UNFURL Using home project at: "/home/stoetzms/.unfurl_home/unfurl.yaml"
   INFO   UNFURL Loaded project at /home/stoetzms/unfurl-ansible-host/unfurl.yaml
   INFO   UNFURL Vault password found, configuring vault ids: ['unfurl-ansible-hostGR', '.unfurl_homeF0']
   INFO   UNFURL Validating TOSCA template at /home/stoetzms/unfurl-ansible-host/ensemble/ensemble.yaml
   INFO   UNFURL Loading ensemble "/home/stoetzms/unfurl-ansible-host/ensemble/ensemble.yaml" in environment "None"
   INFO   TOSCA.MODEL The pre-parsed input successfully passed validation.
   INFO   UNFURL Vault password found, configuring vault ids: ['+%', '.unfurl_homeF0']
   INFO   UNFURL Validating TOSCA template at /home/stoetzms/.unfurl_home/.
   INFO   UNFURL Loading ensemble "/home/stoetzms/.unfurl_home/ensemble/ensemble.yaml" in environment "None"
   INFO   UNFURL creating deploy plan for /home/stoetzms/unfurl-ansible-host/ensemble/ensemble.yaml
 WARNING  UNFURL.TASK Task create for app (reason: add): Configurator render failed
Traceback (most recent call last):
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/planrequests.py", line 830, in _render_request
    task.rendered = task.configurator.render(task)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/configurators/ansible.py", line 278, in render
    inventory = self.get_inventory(task, cwd)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/configurators/ansible.py", line 207, in get_inventory
    return cwd.write_file(inventory, "inventory.yaml")
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/projectpaths.py", line 210, in write_file
    write_file(ctx, contents, path, self.location, encoding, yaml=yaml)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/projectpaths.py", line 578, in write_file
    file.write(obj)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/projectpaths.py", line 353, in write
    save_to_file(path, obj, self.yaml, encoding)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/util.py", line 432, in save_to_file
    dump(obj, f, path, yaml, encoding)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/util.py", line 375, in dump
    (yaml or _yaml).dump(obj, f)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/ruamel/yaml/main.py", line 574, in dump
    return self.dump_all([data], stream, transform=transform)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/ruamel/yaml/main.py", line 583, in dump_all
    self._context_manager.dump(data)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/ruamel/yaml/main.py", line 915, in dump
    self._yaml.representer.represent(data)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 80, in represent
    node = self.represent_data(data)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 113, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/stoetzms/unfurl-1.0.0/.venv/lib/python3.10/site-packages/unfurl/yamlloader.py", line 140, in represent_undefined
    raise RepresenterError(msg)
ruamel.yaml.representer.RepresenterError: cannot represent an object: <{'all': {'hosts': {'host': {'ansible_host': 'hardcoded_ansible_host', 'ansible_connection': 'ssh'}}, 'vars': {}, 'children': {}}}> of type <class 'unfurl.result.ResultsMap'>
   INFO   UNFURL Plan for deploy:

Node "host" (pending):
- operation create (reason: add)
   rendered at /home/stoetzms/unfurl-ansible-host/ensemble/planned/tasks/host/create
  ERROR   UNFURL Aborting job: there were errors during rendering: [UnfurlTaskError("Configurator render failed: cannot represent an object: <{'all': {'hosts': {'host': {'ansible_host': 'hardcoded_ansible_host', 'ansible_connection': 'ssh'}}, 'vars': {}, 'children': {}}}> of type <class 'unfurl.result.ResultsMap'>")]
````

I have tried various variations.

Also, is it possible to access the public address attribute of the host using the inventory input, e.g., using `ansible_host: {eval: '.::..::.requirements[.name=host]::.target::public_address'}`?

Best Greetings
Miles

**Comment by aszs** [comment]
That exception was a bug, the parsing error goes away after I fixed it on our testing branch. If you want to use the branch, you can install it like this: `pip install -U git+https://github.com/onecommons/unfurl@testing`. Otherwise, we'll do a patch release with that fix soon.  Thanks for reporting that!

**Comment by milesstoetzner** [comment]
Thank you! I will wait for thr next release. Thus, you might close this issue for now.
